apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
images:
- name: sce06147/gitops
  newTag: faec24760c6b3a6ff7418372ac2d8f970dd2decf
