apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
images:
- name: sce06147/gitops
  newTag: 576a8a9de1af5e45d880f872b45ce4e340d381ef
